# ***이미지도 결국 숫자일 뿐입니다***
- 먼저 카메라앱을 이용해 동영상을 만듭니다
- 만든 동영상으로부터 프레임을 추출합니다
- 프레임으로부터 숫자를 추출하여 텍스트 파일로 만들어서 숫자가 어떻게 기록되어 있는지 확인합니다
- 숫자를 다시 이미지파일로 만들고 열어봅니다
  - 이 시점에서 이미지 = 숫자 인정

In [ ]:
! pip install opencv-python numpy==2.1 ultralytics

## ***동영상으로부터 이미지 추출하기***
- fps: 1초를 구성하는 이미지 수 정보
- 아래 코드를 실행후 frames폴더에 저장되는 이미지를 확인해봅니다

In [ ]:
import cv2
import os

video_path = "movie.mp4"
output_dir = "frames"

os.makedirs(output_dir, exist_ok=True)

cap = cv2.VideoCapture(video_path)
fps = cap.get(cv2.CAP_PROP_FPS)

frame_idx = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    filename = f"frame_{frame_idx:06d}.jpg"
    cv2.imwrite(os.path.join(output_dir, filename), frame)

    frame_idx += 1

cap.release()

print(f"초당 {fps}프레임, 총 {frame_idx} 프레임 저장 완료")


## ***n초 시점의 이미지 읽기***

In [ ]:
import cv2
import os


#################################################
# 이곳을 동영상의 범위 내에서 변화시키면서 실행해봅니다 #
#################################################
n_sec = 1.8

frames_dir = "frames"
fps = 30

frame_idx = int(n_sec * fps)

filename = f"frame_{frame_idx:06d}.jpg"
img_path = os.path.join(frames_dir, filename)

if not os.path.exists(img_path):
    raise FileNotFoundError(f"{img_path} 없음")

img = cv2.imread(img_path)

print(f"{n_sec}초 -> frame {frame_idx}")

cv2.imshow(f"{n_sec}s image", img)

while True:
    key = cv2.waitKey(0) & 0xFF
    if key == 27:  # ESC 키
        break

cv2.destroyAllWindows()


## ***이미지의 내부 확인해보기***
- 이미지의 내용은 아래와 같습니다
- 3개씩 묶인 숫자들이 있습니다
- 숫자의 범위는 0이상이고 255를 넘지 않습니다

In [ ]:
img

## ***숫자로 이미지 만들기***
- 아래 코드는 이미지를 읽어서 숫자를 만들지 않습니다
- 대신 숫자를 임의로 만들어서 이미지로 만듭니다

In [ ]:
import numpy as np
import cv2

#############################################
# 아래 cells와 cell_px를 바꾸면서 테스트해봅니다 #
#############################################
cells = 50
cell_px = 10

board = (np.indices((cells, cells)).sum(axis=0) % 2) * 255
board = board.astype(np.uint8)

board_px = np.kron(board, np.ones((cell_px, cell_px), dtype=np.uint8))

img = np.stack([board_px, board_px, board_px], axis=-1)

print(img.shape)
img


## ***숫자로 만든 이미지 시각화하기***

In [ ]:
cv2.imshow("checker", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## ***숫자로 만든 이미지를 jpg파일로 저장하기***

In [ ]:
import numpy as np
import cv2

#############################################
# 아래 cells와 cell_px를 바꾸면서 테스트해봅니다 #
#############################################
cells = 50
cell_px = 10

board = (np.indices((cells, cells)).sum(axis=0) % 2) * 255
board = board.astype(np.uint8)

board_px = np.kron(board, np.ones((cell_px, cell_px), dtype=np.uint8))

img = np.stack([board_px, board_px, board_px], axis=-1)

cv2.imwrite('checker.jpg', img)


## ***숫자로 만든 jpg파일을 다시 읽어보기***

In [ ]:
import numpy as np
import cv2

img = cv2.imread('checker.jpg')

print(img.shape)

cv2.imshow("checker", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img

## ***핑크색 바둑판 만들기***
- 바둑판의 색을 바꾸면서 색상이 결국 숫자였음을 이해합니다

In [ ]:
import numpy as np
import cv2

########################################################
# 아래 숫자를 0 ~ 255사이 범위내에서 바꾸면서 테스트 해봅니다 #
########################################################
color = [255, 0, 255]

cells = 50
cell_px = 10

board = (np.indices((cells, cells)).sum(axis=0) % 2) * 255
board = board.astype(np.uint8)

board_px = np.kron(board, np.ones((cell_px, cell_px), dtype=np.uint8))

img = np.ones((board_px.shape[0], board_px.shape[1], 3), dtype=np.uint8) * 255

pink = np.array(color, dtype=np.uint8)

img[board_px == 0] = pink

print(img.shape)
img


In [ ]:
cv2.imshow("checker", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## ***매우 작은 이미지 만들기***
- 지금부터는 이미지의 픽셀 배치를 알아볼 것입니다
- 그래서 3x3 또는 5x5 이미지를 만들고 숫자의 내용을 확인해봅니다
- 실제 이미지와 비교하면서 각 픽셀이 어떻게 배치되었는지 확인합니다
- 결국 색상하나가 픽셀 하나임을 이해하고 결국 이미지가 숫자임을 이해합니다

In [61]:
import numpy as np
import cv2

########################################################
# 아래 숫자를 0 ~ 255사이 범위내에서 바꾸면서 테스트 해봅니다 #
########################################################
color = [128, 128, 128]

cells = 3
cell_px = 1

board = (np.indices((cells, cells)).sum(axis=0) % 2) * 255
board = board.astype(np.uint8)

board_px = np.kron(board, np.ones((cell_px, cell_px), dtype=np.uint8))

img = np.ones((board_px.shape[0], board_px.shape[1], 3), dtype=np.uint8) * 255

pink = np.array(color, dtype=np.uint8)

img[board_px == 0] = pink

print(img.shape)
print(img)
cv2.imwrite('small.png', img)

(3, 3, 3)
[[[128 128 128]
  [255 255 255]
  [128 128 128]]

 [[255 255 255]
  [128 128 128]
  [255 255 255]]

 [[128 128 128]
  [255 255 255]
  [128 128 128]]]


True

## ***이미지를 텍스트 파일로 저장하기***
- 위에서 화면에 출력한 숫자들을 그대로 텍스트파일로 기록합니다

In [64]:
txt_path = "img_data.txt"

with open(txt_path, "w") as f:
    f.write(f"{img.shape[0]} {img.shape[1]} {img.shape[2]}\n")
    pixels = img.flatten()
    f.write(" ".join(map(str, pixels)))

## ***텍스트 파일을 읽어서 이미지로 표시하기***
- 텍스트를 읽어서 이미지로 만들 수 있습니다
- 텍스트에 적힌 것은 결국 숫자였습니다

In [ ]:
txt_path = "img_data.txt"

with open(txt_path, "r") as f:
    lines = f.readlines()
    h, w, c = map(int, lines[0].strip().split())
    pixel_values = np.array(list(map(int, lines[1].strip().split())), dtype=np.uint8)
    img_restored = pixel_values.reshape((h, w, c))

cv2.imwrite("restored.png", img_restored)

복원된 이미지 saved as restored.png


## ***YOLO 모델로 이미지 내의 객체 탐지하기***
- 객체 탐지란 객체의 종류와 위치를 탐지하는 것입니다
- 이미지 내에 어떤 사물이 있는지 서술할 수 있습니다
- 객체의 위치는 좌표, 즉 숫자로 나오게 됩니다
- 객체의 종류는 어떻게 나오게 될까요? 숫자입니다
- 결국 이미지도, 객체탐지도 숫자임을 알게 됩니다

In [ ]:
from ultralytics import YOLO
import cv2
import os

#######################################
# n초 시점의 이미지로부터 객체를 탐지합니다 #
#######################################
n_sec = 1.8

frames_dir = "frames"
fps = 30

frame_idx = int(n_sec * fps)

filename = f"frame_{frame_idx:06d}.jpg"

model = YOLO("yolov8n.pt")

img = cv2.imread(os.path.join(frames_dir, filename))

results = model(img)

annotated = results[0].plot()

for i, box in enumerate(results[0].boxes):
    x1, y1, x2, y2 = box.xyxy[0].tolist()
    cls_id = int(box.cls[0])
    conf = float(box.conf[0])

    print(f"[{i}] class={cls_id} ({model.names[cls_id]}), "
          f"conf={conf:.3f}, "
          f"bbox=({x1:.1f}, {y1:.1f}, {x2:.1f}, {y2:.1f})")

cv2.imshow("detect", annotated)
cv2.waitKey(0)
cv2.destroyAllWindows()


## ***객체탐지 모델의 사전***
- 객체의 id인 숫자가 실제 우리의 언어로 매핑된 정보입니다

In [ ]:
model.names